// src/lib/Carousel.svelte
<script>
	import { beforeUpdate, onMount } from 'svelte';

	let images = ['water', 'bridge', 'hairpin', 'pool'];
	let currentNumber = 0;
	let timer = null;
	let supportsWebP = false;
	let initialized = false;

	function startRotation() {
		timer = setInterval(loop, 5000);
	}

	function stopRotation() {
		clearTimeout(timer);
		timer = null;
	}

	function loop() {
		currentNumber += 1;
		if (currentNumber === 4) currentNumber = 0;
	}

	// source: https://stackoverflow.com/questions/5573096/detecting-webp-support
	function canUseWebP() {
		return document.createElement('canvas').toDataURL('image/webp').indexOf('data:image/webp') == 0;
	}

	function setBackground(node, image) {
		const fileType = supportsWebP ? 'webp' : 'jpg';
		node.style.backgroundImage = `url('/carousel/${image}.${fileType}')`;
	}

	beforeUpdate(() => {
		if (!initialized) {
			supportsWebP = canUseWebP();
			initialized = true;
		}
	});

	onMount(() => {
		startRotation();
	});
</script>

{#each images as image, i}
	<div
		use:setBackground={image}
		class:active={currentNumber === i}
		class="carousel-image absolute inset-0 opacity-0 invisible bg-center
    bg-cover bg-no-repeat"
	/>
{/each}

<div class="carousel-overlay flex-auto flex flex-col justify-center items-center
  text-white">
	<h1 class="carousel-title text-6xl">
		<slot name="title" />
	</h1>
	<h2 class="carousel-subtitle text-4xl">
		<i>
			<slot name="subtitle" />
		</i>
	</h2>
</div>

<style style lang="postcss">
	.carousel-image {
		transition: all 2000ms ease 0s;
		z-index: -1;
	}

	.carousel-overlay {
		background: rgba(0, 0, 0, 0.2);
	}

	.carousel-title,
	.carousel-subtitle {
		text-shadow: 0px 2px 3px black;
	}

	.carousel-title {
		font-weight: 700;
	}
	.carousel-subtitle {
		font-weight: 600;
	}

	.active {
		@apply visible opacity-100;
	}
</style>

// src/components/Carousel.vue
<template>
  <div class="carousel-wrap">
    <div class="carousel">
      <div
        v-for="(image, index) in images"
        :key="index"
        class="carousel__image"
        :class="{ active: currentNumber === index }"
        v-bind:style="{
          backgroundImage: `url('/carousel/${image}.jpg')`
        }"
      ></div>
    </div>

    <div class="carousel__overlay">
      <h1>ZAAHIR MOOLLA</h1>
      <h2><i>moollaza</i></h2>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      images: ["water", "record-player", "hairpin", "hotel-pool"],
      currentNumber: 0,
      timer: null
    };
  },

  mounted: function() {
    this.startRotation();
  },

  methods: {
    startRotation: function() {
      this.timer = setInterval(this.loop, 5000);
    },

    stopRotation: function() {
      clearTimeout(this.timer);
      this.timer = null;
    },

    loop: function() {
      this.currentNumber += 1;
      if (this.currentNumber === 4) this.currentNumber = 0;
    }
  }
};
</script>

<style lang="scss" scoped>
.carousel {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  width: 100vw;
  height: 100vh;

  &__image {
    width: 100%;
    height: 100%;
    position: absolute;
    background: center center no-repeat;
    background-size: cover;
    opacity: 0;
    visibility: hidden;
    transition: all 1000ms ease 0s;
  }

  &__overlay {
    position: absolute;
    display: flex;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    color: white;
    background: rgba(0, 0, 0, 0.1);

    h1,
    h2 {
      text-shadow: 0px 2px 3px black;
    }
  }
}

.active {
  visibility: visible;
  opacity: 1;
}
</style>
